sudo: false
language: java
jdk:
  - openjdk7
before_script:
  - sudo apt-get -qq update > /dev/null
  - sudo apt-get -qq install graphviz > /dev/null
  - chmod +x update-gh-pages.sh
  - mysql -e 'create database myapp_test;'
services:
  - mysql
  - redis-server
cache:
  directories:
  - $HOME/.m2
install: true
script:
  - mvn clean compile cobertura:cobertura
after_success:
  - mvn coveralls:report
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.SONATYPE_USERNAME}</username><password>\${env.SONATYPE_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      mvn deploy --settings ~/settings.xml  -DskipTests;
    fi
  - if [[ "$TRAVIS_BRANCH" == "releases" ]]; then
      mvn release:prepare release:perform --settings ~/settings.xml  -DskipTests -Darguments="-Dmaven.test.skip=true -DskipTests";
    fi
env:
  global:
  - secure: EQ0gLiDj+vMXhjeE+yPCaGdsEshapNH/JVc/f0nwGc4Z3uzC6/8mK4/eYZ9pAcMXoO5sQjBGVFS2e8wOvnOUTs9hSkV3/NXmL2R/AGbHRGr/mkVRkq3FcjC7YB2dNdVLLFdEIA/dviQXwyFqkiQ28wvVEz65BjYSEcqGiJ1BLgA=
